server:
  port: 8081

spring:
  application:
    name: producer
  kafka:
    topic: test
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    acks: all
    retries: 5
    batch-size: 32768
    linger-ms: 10
    compression-type: snappy

